name = "JacobiElliptic"
uuid = "2a8b799e-c098-4961-872a-356c768d184c"
authors = ["dominicchang <dochang@g.harvard.com>"]
version = "0.2.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
JacobiEllipticEnzymeExt = "Enzyme"
JacobiEllipticForwardDiffExt = "ForwardDiff"
JacobiEllipticZygoteExt = "Zygote"

[compat]
DocStringExtensions = "0.9"
Documenter = "1.1"
Enzyme = "0.11, 0.12"
Zygote = "0.6"
ForwardDiff = "0.10"
Setfield = "1.1"
StaticArrays = "1.6"
julia = "1.8"
